# Series ( 1D Label )

In [2]:
import pandas as pd
temperatures = [39, 36 , 33]
days = ['Monday' , 'Tuesday' , 'Wednesday'] 
temp_series = pd.Series( data = temperatures , index = days)
print(temp_series)

Monday       39
Tuesday      36
Wednesday    33
dtype: int64

# DataFrame (2D Tabular Data )

In [19]:
data = {
    'Name' : ['Reach' , 'Vat' , 'Votana' ],
    'Age' : [18 , 29 , 30 ],
    'City' : ['Prey Veng' , 'Phnom Penh ' , 'Steng Treang ']
}
df = pd.DataFrame(data)
# data_series = pd.Series(data = data['Name'] , index =data['City'])
# data_series = df.set_index('City')['Name']
# print(data_series)

               City
row1      Prey Veng
row3  Steng Treang

# The Core Concept

In [ ]:
# Reading Data ( Input ) 
df

# Viewing Data

* Using : .head() to outcome the first Data by we determine a row that we would want to see
* Using : .tail() contrast from Using .head()
* Using : .sample() to random a data and it works as row

In [27]:
df.head(1)
# df.tail(1)
# df.sample(1)

    Name  Age        City
0  Reach    18  Prey Veng

# Understanding Structure  

 These commands tell you about your data size, types, and labels rather than the data values themselves. (Note: attributes like shape, columns, and index do not use parentheses '()').
- .info(): Provides a concise summary of the dataset. It shows the number of rows/columns, the data type of each column (text, integer, decimal), and how many non-blank (non-null) values exist.
- .shape: Returns a tuple showing the dimensions of the data: (number_of_rows, number_of_columns).
- .columns: Returns a list of all the column names. Helpful when you have dozens of columns and need the exact spelling.
- .index: Returns information about the row labels (how the rows are numbered or named).

In [13]:
df.info()
# df.shape
# df.columns
# print(df.index)

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3 entries, 0 to 2
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   Name    3 non-null      object
 1   Age     3 non-null      int64
 2   City    3 non-null      object
dtypes: int64(1), object(2)
memory usage: 204.0+ bytes

# Summary Statistics 
These methods give you a mathematical or categorical summary of the information in your columns.
- .describe(): Calculates quick statistical summaries for all numeric columns (count, mean, standard deviation, min, max, and percentiles).
- .value_counts(): Counts how many times each unique value appears in a specific column. Highly useful for categorical data (like seeing how many people are in each department).

In [17]:
# df.describe() 
df.value_counts()

Name    Age   City
Reach   18    Prey Veng        1
Vat     29    Phnom Penh       1
Votana  30    Steng Treang     1
Name: count, dtype: int64

# Column Selection : df['column'] vs df.column 
- df['column'] (Bracket style): This is the safest and most reliable method. It works for any column name, even if the name has spaces (e.g., df['First Name']) or matches a built-in Python function.
- df.column (Attribute style): This is a handy shortcut for typing quickly, but it fails if your column name has spaces, special characters, or shares a name with a pandas method (like .min or .sum).

In [16]:
# df['Name']
df.Name

<bound method DataFrame.min of      Name  Age            City
0   Reach    18      Prey Veng
1     Vat    29    Phnom Penh
2  Votana    30  Steng Treang >

# Label Based Indexing : .loc[]
- Explanation: Think of .loc as "locate by name." You use the exact text labels of your rows and columns to find data.
- Key rule: When you slice with .loc (e.g., A:C), it includes the last item.

In [35]:
data = {
    'Name' : ['Reach' , 'Vat' , 'Votana' ],
    'Age' : [18 , 29 , 30 ],
    'City' : ['Prey Veng' , 'Phnom Penh ' , 'Steng Treang ']
}
df = pd.DataFrame(data)
df.index = ['row1', 'row2' ,'row3'] 
df.loc[['row1', 'row2'] , ['Name' , 'Age' ]]

       Name  Age
row1  Reach   18
row2    Vat   29

## Integer-based Indexing: .iloc[]

- Explanation: Think of .iloc as "locate by index (number)." You use the numerical position (0, 1, 2...) exactly like you would with standard Python lists.
- Key rule: When you slice with .iloc (e.g., 0:2), it goes up to but does not include the last number.

In [37]:
df.iloc[0:3 , 0:2 ]

        Name  Age
row1   Reach   18
row2     Vat   29
row3  Votana   30

## Filtering (Boolean Condition)